"use client";
import { FormEvent, useState } from "react";

export function ContactForm() {
  const [sent, setSent] = useState(false);
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (event.currentTarget.checkValidity()) { setSent(true); event.currentTarget.reset(); } }
  const fieldClass = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-green-600 focus:ring-4 focus:ring-green-100";
  return <form onSubmit={handleSubmit} className="rounded-3xl border border-green-900/8 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-black text-green-950">Envie uma mensagem</h2><p className="mt-2 text-sm leading-6 text-slate-600">Preencha os dados abaixo. Nesta versão demonstrativa, o formulário não envia informações.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Nome <span aria-hidden="true" className="text-orange-600">*</span><input name="nome" required minLength={2} autoComplete="name" className={fieldClass}/></label><label className="text-sm font-bold text-slate-700">Telefone <span aria-hidden="true" className="text-orange-600">*</span><input name="telefone" required minLength={8} inputMode="tel" autoComplete="tel" className={fieldClass}/></label><label className="text-sm font-bold text-slate-700">E-mail <span aria-hidden="true" className="text-orange-600">*</span><input name="email" type="email" required autoComplete="email" className={fieldClass}/></label><label className="text-sm font-bold text-slate-700">Assunto <span aria-hidden="true" className="text-orange-600">*</span><select name="assunto" required defaultValue="" className={fieldClass}><option value="" disabled>Selecione</option><option>Informações sobre produtos</option><option>Pedido para varejo</option><option>Pedido para atacado</option><option>Outro assunto</option></select></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Mensagem <span aria-hidden="true" className="text-orange-600">*</span><textarea name="mensagem" required minLength={10} rows={5} className={fieldClass}/></label></div><button type="submit" className="button-primary mt-6">Enviar mensagem</button>{sent && <p role="status" className="mt-5 rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-900">Mensagem preenchida com sucesso. A integração de envio será implementada posteriormente; para atendimento imediato, use o WhatsApp.</p>}</form>;
}
